# Generated by Django 3.1.1 on 2020-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200929_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleform',
            name='Zustimmung',
            field=models.BooleanField(default=True),
        ),
    ]
